### PR TITLE
Use zod for validation

### PR DESCRIPTION
**Pull request by ValentinH**
The best argument for `zod` is not to have to maintain side by side the type and the schema. In this simple example, it's less obvious though.

As @balzdur was saying, it's stricter especially when using Numbers so we have to be a bit more careful with the data we pass to our form. However, I don't think this is a blocker.

### CODE REVIEW

**Review by jpb06 — APPROVED** [review]
Looks great. What about this? https://github.com/fabien0102/ts-to-zod

**Comment by ValentinH** [comment]
> Looks great. What about this? [fabien0102/ts-to-zod](https://github.com/fabien0102/ts-to-zod)

I think I prefer the original approach of zod of writing the Schema and inferring the types for (at least) 2 reasons:
- no build command (compared to `ts-to-zod`)
- full access to the `zod` api for advanced validation use cases. If one is not supported by a decorator of `ts-to-zod` we would have to write/contribute it.

I think the main goal of both tools is to only write once and I think that `zod` does it well.

What do you prefer in `ts-to-zod` ?

**Comment by balzdur** [comment]
I agree, runtime validation can be seen as a superset of static type checking.
So IMHO, this package approach is not the best one

**Comment by jpb06** [comment]
Righto. I found the idea interesting but your points make sense. 👍🏻 
My idea was we may have used this package to generate validation schemas from the backend types pulled using https://github.com/jpb06/swagger-typescript-types

**Pull request merged**
